### ISSUE TITLE
When will the code be open？

### ISSUE THREAD

**Issue by Andy20178** [homothetic/Topo2D#1]
Your work is amazing! It shows that the method of introducing 2D images directly increases the Top_ll by 100%. I appreciate your work very much. When do you plan to make the complete code public?

**Comment by homothetic** [comment]
Thank you for your appreciation. The code and models will be released within a week.

**Comment by Andy20178** [comment]
Thank you, looking forward to your code! :)

**Comment by Andy20178** [comment]
In addition, have you tried increasing the number of training epochs? I found that for some models, i.e., TopoNet, after increasing epochs, the scores of Top_ll and Top_lt will increase significantly (although they are still lower than your results).

**Comment by Andy20178** [comment]
Do you have the code ready?

**Comment by homothetic** [comment]
Yes, we extended the training time to 48 epochs and observed that the results for Top_ll and Top_lt increased to 25.3 and 26.7, respectively.
