### ISSUE TITLE
OpenLane v1 cannot reproduce paper metrics

### ISSUE THREAD

**Issue by whuhangzhang** [homothetic/Topo2D#5]
Thanks to the excellent work of the author, I have used your code to reproduce the openlane v1 dataset, and the indicators after training are shown below. I cannot reproduce the F1 indicators in your paper, please give me some suggestions, thank you very much！

感谢作者优秀的工作，我使用您的代码对openlane v1数据集进行了复现，训练后的指标如下所示，无法复现您论文上的F1指标，请给我一些建议，非常感谢

<img width="1766" alt="result" src="https://github.com/user-attachments/assets/76992c11-7582-48fe-9713-4249dd3bf6b1">

**Comment by matthew-wave** [comment]
Hello, I used the v1 dataset according to the code provided by the author, but it keeps getting errors. May I ask if there is any code that needs to be changed during the process of reproducing v1?

**Comment by matthew-wave** [comment]
> Thanks to the excellent work of the author, I have used your code to reproduce the openlane v1 dataset, and the indicators after training are shown below. I cannot reproduce the F1 indicators in your paper, please give me some suggestions, thank you very much！
> 
> 感谢作者优秀的工作，我使用您的代码对openlane v1数据集进行了复现，训练后的指标如下所示，无法复现您论文上的F1指标，请给我一些建议，非常感谢
> 
> <img alt="result" width="1766" src="https://private-user-images.githubusercontent.com/53819630/357393012-76992c11-7582-48fe-9713-4249dd3bf6b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzODA0NjQsIm5iZiI6MTcyODM4MDE2NCwicGF0aCI6Ii81MzgxOTYzMC8zNTczOTMwMTItNzY5OTJjMTEtNzU4Mi00OGZlLTk3MTMtNDI0OWRkM2JmNmIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDA5MzYwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiMWU2OGVkYTY4MDJhODgxMWM3MGYxNDU2MWM3NDFlMGZhOTQwZWM1YmEyZGYyNjc4NzkwZjY5MzAwNmE1ZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6Xhi9IlLxyuNQhalfXrEj4Ru4xPR3yp0OKk1Z8pyRvw">

Hello, I used the v1 dataset according to the code provided by the author, but it keeps getting errors. May I ask if there is any code that needs to be changed during the process of reproducing v1?
![Uploading 微信图片_20241008173757.png…]()

**Comment by matthew-wave** [comment]
Hello, I used the v1 dataset according to the code provided by the author, but it keeps getting errors. May I ask if there is any code that needs to be changed during the process of reproducing v1? Please tell me your replication method and key points.
你好，我按照作者提供的代码使用了v1的数据集，但是一直报错。请问你在复现v1的过程中有需要更改的代码吗？请你告诉我你的复现方法和要点。如果方便，还请你告诉我你的邮箱。

**Comment by ppbangKGT** [comment]
> Thanks to the excellent work of the author, I have used your code to reproduce the openlane v1 dataset, and the indicators after training are shown below. I cannot reproduce the F1 indicators in your paper, please give me some suggestions, thank you very much！
> 
> 感谢作者优秀的工作，我使用您的代码对openlane v1数据集进行了复现，训练后的指标如下所示，无法复现您论文上的F1指标，请给我一些建议，非常感谢
> 
> <img alt="result" width="1766" src="https://private-user-images.githubusercontent.com/53819630/357393012-76992c11-7582-48fe-9713-4249dd3bf6b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1Mjg1NjcsIm5iZiI6MTczMjUyODI2NywicGF0aCI6Ii81MzgxOTYzMC8zNTczOTMwMTItNzY5OTJjMTEtNzU4Mi00OGZlLTk3MTMtNDI0OWRkM2JmNmIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDA5NTEwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkOWIzZWMzNzU0YWQzNzA2MWQ4ZmZhN2ZkMzc4YzJhZTYxYTkyOWY3ZTg1ZmQ1YzE2NjVkZjg0ZjBjMjZjOTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ie6DQ8-KqGcccf_Fp0jI13T0W81xYH0X5IwHNgbNAfg">

i got a similar result like you. have you solved it?

**Comment by JokeQ666** [comment]
> 感谢作者的出色工作，我用你们的代码复现了 openlane v1 数据集，训练后的指标如下图。我无法复制您论文中的 F1 指标，请给我一些建议，非常感谢！
> 
> 感谢作者优秀的工作，我使用您的代码对openlane v1数据集进行了复现，训练后的指标如下所示，无法复现您论文上的F1指标，请给我一些建议，非常感谢
> 
> <img alt="result" width="1766" src="https://private-user-images.githubusercontent.com/53819630/357393012-76992c11-7582-48fe-9713-4249dd3bf6b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyNTAyNzMsIm5iZiI6MTczNDI0OTk3MywicGF0aCI6Ii81MzgxOTYzMC8zNTczOTMwMTItNzY5OTJjMTEtNzU4Mi00OGZlLTk3MTMtNDI0OWRkM2JmNmIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE1VDA4MDYxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3MWNmZmRmYjY5OWUxMzc5MjllNmQ3NWY4Yjg3YTQ4NGE1YzMyMDQ1MzI1NWI5YzUxOGJkY2ZiMTFiZGNhYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LZ6aRaNEWO5MPwZAGxum4JCYBypQ0XgLyd9MRFvLZrw">

你好，我是初学者，感觉这个方向数据集有点大，想问下你用什么卡训练的，整个训练过程花了多少时间？

**Comment by matthew-wave** [comment]
> > 感谢作者的出色工作，我用你们的代码复现了 openlane v1 数据集，训练后的指标如下图。我无法复制您论文中的 F1 指标，请给我一些建议，非常感谢！
> > 感谢作者优秀的工作，我使用您的代码对openlane v1数据集进行了复现，训练后的指标如下所示，无法复现您论文上的F1指标，请给我一些建议，非常感谢
> > <img alt="result" width="1766" src="https://private-user-images.githubusercontent.com/53819630/357393012-76992c11-7582-48fe-9713-4249dd3bf6b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyNTAyNzMsIm5iZiI6MTczNDI0OTk3MywicGF0aCI6Ii81MzgxOTYzMC8zNTczOTMwMTItNzY5OTJjMTEtNzU4Mi00OGZlLTk3MTMtNDI0OWRkM2JmNmIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE1VDA4MDYxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3MWNmZmRmYjY5OWUxMzc5MjllNmQ3NWY4Yjg3YTQ4NGE1YzMyMDQ1MzI1NWI5YzUxOGJkY2ZiMTFiZGNhYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LZ6aRaNEWO5MPwZAGxum4JCYBypQ0XgLyd9MRFvLZrw">
> 
> 你好，我是初学者，感觉这个方向数据集有点大，想问下你用什么卡训练的，整个训练过程花了多少时间？
I haven't trained, but I can tell you the time and device parameters for using OpenLaneV1 inference.
I used two V100 (40GB) and inferred a scene (about 199 images) in 5 minutes. Set batchresize to 1.
It should be noted that although I used two cards, only one actually participated in the inference, but switching to running on a single card would result in an error. The author also recommends single machine multi card training and inference. Currently, I have not made any changes to the code that runs on a single card. If you have any progress, please let me know.
